/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1emilio.interfaz;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Emilio Jr
 */
public class Menu extends javax.swing.JFrame {

        /**
         * Creates new form Menu
         */
        public Menu() {
                initComponents();
                this.setLocationRelativeTo(null);
                this.getContentPane().setBackground(Color.BLACK);
                this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                irSelection = new javax.swing.JButton();
                exitButton = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 0, 0));
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

                jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 24)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 0));
                jLabel1.setText("GENERADOR DE LABERINTOS");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

                jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 0, 0));
                jLabel2.setText("¡BIENVENIDO!");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 30));

                jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("Seleccione una de las opciones:");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

                irSelection.setBackground(new java.awt.Color(0, 0, 102));
                irSelection.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
                irSelection.setForeground(new java.awt.Color(255, 255, 255));
                irSelection.setText("GENERAR LABERINTO");
                irSelection.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                irSelectionActionPerformed(evt);
                        }
                });
                getContentPane().add(irSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 200, 70));

                exitButton.setBackground(new java.awt.Color(0, 0, 102));
                exitButton.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
                exitButton.setForeground(new java.awt.Color(255, 255, 255));
                exitButton.setText("SALIR");
                exitButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitButtonActionPerformed(evt);
                        }
                });
                getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 264, 200, 60));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void irSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irSelectionActionPerformed
                // TODO add your handling code here:
                Selection abrir = new Selection();
                abrir.setVisible(true);
                this.setVisible(false);

        }

        }//GEN-LAST:event_irSelectionActionPerformed

        private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_exitButtonActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;

}
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Menu.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Menu.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Menu.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Menu.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Menu().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton exitButton;
        private javax.swing.JButton irSelection;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        // End of variables declaration//GEN-END:variables
}
