/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto1emilio.interfaz;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author Emilio Jr
 */
public class Selection extends javax.swing.JFrame {

        /**
         * Creates new form Selection
         */
        public Selection() {
                initComponents();
                this.setLocationRelativeTo(null); 
                this.getContentPane().setBackground(Color.BLACK);
                this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                wallFollower = new javax.swing.JButton();
                DFS = new javax.swing.JButton();
                BFS = new javax.swing.JButton();
                jLabel2 = new javax.swing.JLabel();
                weidth = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                rowNum = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                columnsNum = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
                getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

                jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("SELECCIONE COMO DESEA SOLUCIONAR EL LABERINTO");
                getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

                wallFollower.setBackground(new java.awt.Color(153, 255, 255));
                wallFollower.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
                wallFollower.setForeground(new java.awt.Color(0, 0, 0));
                wallFollower.setText("WALL FOLLOWER");
                getContentPane().add(wallFollower, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

                DFS.setBackground(new java.awt.Color(153, 255, 153));
                DFS.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
                DFS.setForeground(new java.awt.Color(0, 0, 0));
                DFS.setText("DEPTH FIRST SEARCH");
                getContentPane().add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

                BFS.setBackground(new java.awt.Color(255, 102, 102));
                BFS.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
                BFS.setForeground(new java.awt.Color(0, 0, 0));
                BFS.setText("BREADTH FIRST SEARCH");
                getContentPane().add(BFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

                jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                jLabel2.setText("ESCRIBA EL ANCHO DE LAS CELDAS");
                getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

                weidth.setBackground(new java.awt.Color(255, 255, 255));
                weidth.setForeground(new java.awt.Color(153, 255, 255));
                getContentPane().add(weidth, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 100, -1));

                jLabel3.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                jLabel3.setText("ESCRIBA EL NÚMERO DE FILAS DEL LABERINTO");
                getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                rowNum.setBackground(new java.awt.Color(255, 255, 255));
                rowNum.setForeground(new java.awt.Color(255, 255, 255));
                getContentPane().add(rowNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 100, -1));

                jLabel4.setFont(new java.awt.Font("OCR A Extended", 1, 12)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                jLabel4.setText("ESCRIBA EL NÚMERO DE COLUMNAS DEL LABERINTO");
                getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

                columnsNum.setBackground(new java.awt.Color(255, 255, 255));
                columnsNum.setForeground(new java.awt.Color(153, 255, 255));
                getContentPane().add(columnsNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 100, -1));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
                /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(Selection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                //</editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new Selection().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton BFS;
        private javax.swing.JButton DFS;
        private javax.swing.JTextField columnsNum;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField rowNum;
        private javax.swing.JButton wallFollower;
        private javax.swing.JTextField weidth;
        // End of variables declaration//GEN-END:variables
}
